version: '3'

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - '3000:3000'
    depends_on:
      - movie-service
      - user-service

  movie-service:
    build: ./movie-service
    container_name: movie-service
    ports:
      - '3001:3001'

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - '3002:3002'
